Angry bee behaviour
latedude2/P5Game pull request #82
Opened 2020-11-17 14:16 UTC by MikkMunk

Still needs animation and hurt effect interaction

2020-11-17 14:32 UTC, latedude2 requested changes
YOU FORGOT TO REMOVE MAGIC NUMBERS - Olga

2020-11-17 20:27 UTC, Jokubas126 commented on Assets/Scripts/BeeAngryController.cs
> +        anim = GetComponentInChildren<Animator>();
can we call this `animator`? Just better coding practice and better for readability

2020-11-17 20:29 UTC, Jokubas126 commented on Assets/Scripts/BeeAngryController.cs
> +    }
can we put those separate parts of Update function to smaller functions? Would be easier to understand which part does what

2020-11-17 20:30 UTC, Jokubas126 commented on Assets/Scripts/EndTaskInteraction.cs
> +                angryBeeSpawned = true;
Just better code practice
```suggestion
                hasAngryBeeSpawned = true;
```

2020-11-17 20:34 UTC, Jokubas126 commented on Assets/Scripts/BeeAngryController.cs
> +        float dist = Vector3.Distance(player.position, transform.position);
Please rename it to something that would tell what "distance" is it. Like `agentDistance`, `relativeDistance` or something like that

2020-11-17 20:37 UTC, Jokubas126 commented on Assets/Scripts/BeeAngryController.cs
> +        }
Can we do it on a separate thread if it's heavy as well? `StartCoroutine(IEnumerator coroutine);` should do the job

2020-11-17 20:39 UTC, Jokubas126 commented on Assets/Scripts/BeeAngryController.cs
> +        Debug.Log("DEAD!");
It doesn't work yet or did you forget to uncoment it?

2020-11-17 20:40 UTC, Jokubas126 commented on Assets/Scripts/BeeAngryController.cs
> +        Debug.Log("DEAD!");
oh I saw the PR description. It's ok 😄

2020-11-17 20:41 UTC, Jokubas126 commented on Assets/Scripts/BeeAngryController.cs
> +        }
Some examples here: [https://docs.unity3d.com/ScriptReference/MonoBehaviour.StartCoroutine.html](https://docs.unity3d.com/ScriptReference/MonoBehaviour.StartCoroutine.html)

2020-11-19 09:40 UTC, Jokubas126 approved these changes
Beautiful ❤️

2020-11-19 10:16 UTC, latedude2 approved these changes

2020-11-19 10:17 UTC, merged